#!/usr/bin/env python3
"""
AI Opportunity Radar — Main Report Generator

Usage:
    python scripts/generate_report.py

Outputs:
    - reports/daily/YYYY-MM-DD.md   (Markdown daily report)
    - data/processed/YYYY-MM-DD_items.json  (scored items JSON)
    - data/raw/YYYY-MM-DD_raw.json  (raw collected items, before scoring)
"""
import json
import os
import sys
from datetime import datetime

from dotenv import load_dotenv

load_dotenv()

# Ensure the scripts directory is on the path
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(BASE_DIR, "scripts"))

from collect_github import collect_github
from collect_arxiv import collect_arxiv
from collect_rss import collect_rss
from score_items import score_items
from summarize_llm import summarize_items, apply_fallback_summaries


def generate_report():
    today = datetime.now().strftime("%Y-%m-%d")
    print(f"{'='*60}")
    print(f"  AI Opportunity Radar — {today}")
    print(f"{'='*60}")

    # Phase 1: Collect
    print("\n[1/5] Collecting data...")
    github_items = collect_github()
    arxiv_items = collect_arxiv()
    rss_items = collect_rss()

    all_items = github_items + arxiv_items + rss_items
    print(f"\n  Total collected: {len(all_items)} items")
    print(f"    GitHub: {len(github_items)}, arXiv: {len(arxiv_items)}, RSS: {len(rss_items)}")

    # Save raw data
    raw_dir = os.path.join(BASE_DIR, "data", "raw")
    os.makedirs(raw_dir, exist_ok=True)
    raw_path = os.path.join(raw_dir, f"{today}_raw.json")
    with open(raw_path, "w", encoding="utf-8") as f:
        json.dump(all_items, f, ensure_ascii=False, indent=2, default=str)
    print(f"  Raw data saved: {raw_path}")

    if not all_items:
        print("\n[WARNING] No items collected. Check your network and API access.")
        print("  If you are in China, you may need a VPN to access GitHub API and arXiv.")
        return

    # Phase 2: Score
    print("\n[2/5] Scoring items...")
    scored = score_items(all_items)

    keep_count = sum(1 for i in scored if i.get("level") == "KEEP")
    watch_count = sum(1 for i in scored if i.get("level") == "WATCH")
    ignore_count = sum(1 for i in scored if i.get("level") == "IGNORE")
    print(f"  KEEP: {keep_count}, WATCH: {watch_count}, IGNORE: {ignore_count}")

    # Phase 3: Summarize
    print("\n[3/5] Generating summaries...")
    summarize_items(scored, top_n=10)
    apply_fallback_summaries(scored, top_n=10)

    # Phase 4: Save processed data
    print("\n[4/5] Saving processed data...")
    processed_dir = os.path.join(BASE_DIR, "data", "processed")
    os.makedirs(processed_dir, exist_ok=True)
    processed_path = os.path.join(processed_dir, f"{today}_items.json")
    with open(processed_path, "w", encoding="utf-8") as f:
        json.dump(scored, f, ensure_ascii=False, indent=2, default=str)
    print(f"  Processed data saved: {processed_path}")

    # Phase 5: Generate Markdown report
    print("\n[5/5] Generating Markdown report...")
    report_dir = os.path.join(BASE_DIR, "reports", "daily")
    os.makedirs(report_dir, exist_ok=True)
    report_path = os.path.join(report_dir, f"{today}.md")

    markdown = _build_report_markdown(scored, today)

    with open(report_path, "w", encoding="utf-8") as f:
        f.write(markdown)
    print(f"  Report saved: {report_path}")

    print(f"\n{'='*60}")
    print(f"  Done! Report: reports/daily/{today}.md")
    print(f"{'='*60}")


def _build_report_markdown(scored: list[dict], today: str) -> str:
    """Build the full Markdown daily report."""
    # Sort by final_score descending
    ranked = sorted(scored, key=lambda x: x.get("final_score", 0), reverse=True)

    # Filter by level
    keep_items = [i for i in ranked if i.get("level") == "KEEP"]
    watch_items = [i for i in ranked if i.get("level") == "WATCH"]
    display_items = keep_items + watch_items

    lines = []
    lines.append(f"# AI Opportunity Radar Daily — {today}")
    lines.append("")
    lines.append(f"> Auto-generated by AI Opportunity Radar. {len(scored)} items collected, {len(keep_items)} KEEP, {len(watch_items)} WATCH.")
    lines.append("")

    # ── Top Opportunities ──
    lines.append("## 今日最高价值机会")
    lines.append("")
    top5 = [i for i in ranked if i.get("level") in ("KEEP", "WATCH")][:5]
    if not top5:
        lines.append("*No high-value opportunities found today.*")
        lines.append("")
    else:
        for idx, item in enumerate(top5, 1):
            lines.append(f"### {idx}. {item.get('title', 'Untitled')}")
            lines.append("")
            lines.append(f"- **类型**: {item.get('type', '').upper()} | **来源**: {item.get('source', '')} | **分数**: {item.get('final_score', 0)}")
            lines.append(f"- **链接**: [{item.get('url', '#')}]({item.get('url', '#')})")
            lines.append(f"- **关注理由**: {item.get('why_it_matters', '待评估')}")
            lines.append(f"- **和我的关系**: {item.get('connection_to_me', '待评估')}")
            lines.append(f"- **建议行动**: {item.get('suggested_action', '待评估')}")
            lines.append("")

    # ── GitHub Projects ──
    lines.append("## GitHub 项目")
    lines.append("")
    github_items = [i for i in display_items if i.get("type") == "github"][:10]
    if not github_items:
        lines.append("*No GitHub projects collected today.*")
        lines.append("")
    else:
        lines.append("| # | 项目 | Stars | 分数 | 等级 |")
        lines.append("|---|------|-------|------|------|")
        for idx, item in enumerate(github_items, 1):
            title = item.get("title", "Untitled")
            url = item.get("url", "#")
            stars = item.get("stars", 0)
            score = item.get("final_score", 0)
            level = item.get("level", "")
            level_emoji = "🟢" if level == "KEEP" else "🟡"
            lines.append(f"| {idx} | [{title}]({url}) | {stars} | {score} | {level_emoji} {level} |")
        lines.append("")

        # Details for top GitHub items
        for item in github_items[:5]:
            lines.append(f"### [{item.get('title', '')}]({item.get('url', '#')})")
            lines.append("")
            desc = item.get("description", "").strip()
            if desc:
                lines.append(f"{desc[:300]}")
                lines.append("")
            lines.append(f"- **Stars**: {item.get('stars', 0)} | **Language**: {item.get('language', 'N/A')}")
            lines.append(f"- **关注理由**: {item.get('why_it_matters', '—')}")
            lines.append(f"- **建议行动**: {item.get('suggested_action', '—')}")
            lines.append("")

    # ── arXiv Papers ──
    lines.append("## arXiv 论文")
    lines.append("")
    paper_items = [i for i in display_items if i.get("type") == "paper"][:10]
    if not paper_items:
        lines.append("*No arXiv papers collected today.*")
        lines.append("")
    else:
        lines.append("| # | 论文 | 来源 | 分数 | 等级 |")
        lines.append("|---|------|------|------|------|")
        for idx, item in enumerate(paper_items, 1):
            title = item.get("title", "Untitled")
            url = item.get("url", "#")
            source = item.get("source", "")
            score = item.get("final_score", 0)
            level = item.get("level", "")
            level_emoji = "🟢" if level == "KEEP" else "🟡"
            lines.append(f"| {idx} | [{title}]({url}) | {source} | {score} | {level_emoji} {level} |")
        lines.append("")

        for item in paper_items[:5]:
            lines.append(f"### [{item.get('title', '')}]({item.get('url', '#')})")
            lines.append("")
            authors = item.get("authors", [])
            if authors:
                lines.append(f"**Authors**: {', '.join(authors[:5])}")
                lines.append("")
            desc = item.get("description", "").strip()
            if desc:
                lines.append(f"{desc[:300]}")
                lines.append("")
            lines.append(f"- **Published**: {item.get('published_at', 'N/A')}")
            lines.append(f"- **关注理由**: {item.get('why_it_matters', '—')}")
            lines.append(f"- **建议行动**: {item.get('suggested_action', '—')}")
            lines.append("")

    # ── RSS News ──
    lines.append("## RSS 新闻")
    lines.append("")
    news_items = [i for i in display_items if i.get("type") == "news"][:10]
    if not news_items:
        lines.append("*No RSS news collected today.*")
        lines.append("")
    else:
        lines.append("| # | 标题 | 来源 | 分数 | 等级 |")
        lines.append("|---|------|------|------|------|")
        for idx, item in enumerate(news_items, 1):
            title = item.get("title", "Untitled")
            url = item.get("url", "#")
            source = item.get("source", "")
            score = item.get("final_score", 0)
            level = item.get("level", "")
            level_emoji = "🟢" if level == "KEEP" else "🟡"
            lines.append(f"| {idx} | [{title}]({url}) | {source} | {score} | {level_emoji} {level} |")
        lines.append("")

        for item in news_items[:5]:
            lines.append(f"### [{item.get('title', '')}]({item.get('url', '#')})")
            lines.append("")
            desc = item.get("description", "").strip()
            if desc:
                lines.append(f"{desc[:300]}")
                lines.append("")
            lines.append(f"- **来源**: {item.get('source', '')} | **时间**: {item.get('published_at', 'N/A')}")
            lines.append(f"- **关注理由**: {item.get('why_it_matters', '—')}")
            lines.append(f"- **建议行动**: {item.get('suggested_action', '—')}")
            lines.append("")

    # ── Action Suggestions ──
    lines.append("## 今日行动建议")
    lines.append("")

    # Generate 3 action suggestions based on top items
    top_github = [i for i in ranked if i.get("type") == "github" and i.get("level") in ("KEEP", "WATCH")]
    top_paper = [i for i in ranked if i.get("type") == "paper" and i.get("level") in ("KEEP", "WATCH")]
    top_news = [i for i in ranked if i.get("type") == "news" and i.get("level") in ("KEEP", "WATCH")]

    # Suggestion 1 — clone-worthy repo
    if top_github:
        item = top_github[0]
        lines.append(f"1. **复刻项目**: [{item.get('title', '')}]({item.get('url', '#')}) — {item.get('stars', 0)} stars, 值得深入研究和学习。{item.get('suggested_action', '')}")
    else:
        lines.append("1. **复刻项目**: 今日暂无高价值 GitHub 项目，建议关注 AI agent / RAG / multimodal 相关仓库。")

    # Suggestion 2 — paper for literature review
    if top_paper:
        item = top_paper[0]
        lines.append(f"2. **文献阅读**: [{item.get('title', '')}]({item.get('url', '#')}) — 适合加入你的研究文献库。{item.get('suggested_action', '')}")
    else:
        lines.append("2. **文献阅读**: 今日暂无高价值论文，建议浏览 arXiv 的 cs.AI / cs.CL / cs.CV 板块。")

    # Suggestion 3 — trend to write about
    if top_news:
        item = top_news[0]
        lines.append(f"3. **趋势写作**: [{item.get('title', '')}]({item.get('url', '#')}) — 这个话题值得写成个人网站文章或社交媒体内容。{item.get('suggested_action', '')}")
    else:
        lines.append("3. **趋势写作**: 今日暂无高价值新闻，建议关注 Hacker News 和 Hugging Face Papers 的 AI 趋势。")

    lines.append("")
    lines.append("---")
    lines.append(f"*Report generated at {datetime.now().strftime('%Y-%m-%d %H:%M:%S')} by AI Opportunity Radar*")

    return "\n".join(lines)


if __name__ == "__main__":
    generate_report()
